### ISSUE TITLE
Rename this app to Starcounter.ClientFiles

### ISSUE THREAD

**Issue by warpech** [Starcounter/StarcounterClientFiles#11]
In order to do https://github.com/Starcounter/Home/issues/326, we need to pick a better name for this app. I propose `Starcounter.ClientFiles`.

**Comment by alshakero** [comment]
I think we'll need another name `ScErrBadApplicationName (SCERR2146): Application name can only contain letters, numbers and underscores`.

**Comment by warpech** [comment]
Ugh... `StarcounterClientFiles`?

**Comment by alshakero** [comment]
Closing as done in https://github.com/Starcounter/StarcounterClientFiles/commit/c556ea15ab93431b698aa77769fe3a0335027dbd
