### ISSUE TITLE
Master branch should include all client files for Polymer 1

### ISSUE THREAD

**Issue by warpech** [Starcounter/StarcounterClientFiles#12]
Branch `master` should include all client files for Polymer 1, including `app-shell.html` (see: https://github.com/Starcounter/Home/issues/334).

Basically, this will be a copy of https://github.com/Starcounter/level1/tree/fc4f00ac3d60dc7551c574053514b3fd5700d5ad/src/BuildSystem/ClientFiles including `app-shell.html` for Polymer 1.

When this is done, release branch `master` as Starcounter.ClientFiles 1.0.0

**Comment by warpech** [comment]
This is means to implement https://github.com/Starcounter/Home/issues/326

**Comment by alshakero** [comment]
Ping here https://github.com/Starcounter/KitchenSink/pull/208#issuecomment-350793097 when this is done.

**Comment by alshakero** [comment]
Done in https://github.com/Starcounter/StarcounterClientFiles/commit/4adc2ec793373f18e8e084e64b79d39beaf158e8

**Comment by warpech** [comment]
Just one comment: Bower files should be in the project directory, as in the project structure presented here: https://docs.starcounter.io/cookbook/project-structure

**Comment by alshakero** [comment]
Closing as done in https://github.com/Starcounter/StarcounterClientFiles/commit/da3c1b0a10e6389e939c9deab483303fd7053785

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/StarcounterClientFiles/releases/tag/1.0.0
- included in level1 https://github.com/Starcounter/level1/pull/4420
- announced on the Starcounter blog https://starcounter.io/starcounter-2-4-gets-upgrade-polymer-2/ ("Manual upgrade or downgrade to Polymer 1 and 2")
