### ISSUE TITLE
Master-2.4 branch should include all client files for Polymer 2

### ISSUE THREAD

**Issue by warpech** [Starcounter/StarcounterClientFiles#13]
Branch `master-2.4` should include all client files for Polymer 2, including `app-shell.html` (see: https://github.com/Starcounter/Home/issues/334).

When this is done, release branch `master-2.4` as Starcounter.ClientFiles 2.0.0

**Comment by alshakero** [comment]
Should it include all files in Starcounter/ClientFiles or only Polymer 2.0 related files?

**Comment by warpech** [comment]
All client files, because this is the goal: https://github.com/Starcounter/Home/issues/326

**Comment by alshakero** [comment]
Good? https://github.com/Starcounter/StarcounterClientFiles/tree/master-2.4

**Comment by alshakero** [comment]
If yes, I'll replicate the same format for `master`.

**Comment by warpech** [comment]
Please add `.vs` to `.gitignore` and remove these directories from repo.

I think that the list of dependencies in README.md can be changed by just a link to https://github.com`./src/StarcounterClientFiles/wwwroot/bower-list.txt`. There will be one less thing to maintain.

Other than that yes, it looks as desired!

**Comment by alshakero** [comment]
> There will be one less thing to maintain.

Perfect idea!

**Comment by warpech** [comment]
Please put `bower-list.txt`, `.bowerrc`, `.gitignore`, `bower-list.txt` in more canonical path. In other apps these files are in repo root or in the VS project root.

**Comment by alshakero** [comment]
> Please put bower-list.txt, .bowerrc, .gitignore, bower.json in the canonical path. In other apps, these files are in repo root or in the VS project root. 

Legit point.

Done in https://github.com/Starcounter/StarcounterClientFiles/commit/2d467a680a496e277be9045dbde4965593260f59. 

Good enough to close this?

**Comment by warpech** [comment]
Just a small comment: The canonical way for Bower files is to put them in the project directory, as in the project structure presented here: https://docs.starcounter.io/cookbook/project-structure

**Comment by alshakero** [comment]
Closing as done in https://github.com/Starcounter/StarcounterClientFiles/commit/a448db7ba3fbcd02983eede2ed5ede9d1544f691

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/StarcounterClientFiles/releases/tag/2.0.0
- included in level1 https://github.com/Starcounter/level1/pull/4435
- announced on the Starcounter blog https://starcounter.io/starcounter-2-4-gets-upgrade-polymer-2/ ("Manual upgrade or downgrade to Polymer 1 and 2")
