### ISSUE TITLE
Release versions for App Warehouse

### ISSUE THREAD

**Issue by warpech** [Starcounter/StarcounterClientFiles#14]
The current `master` branch should be tagged `1.0.0`, built with Starcounter 2.4, packaged for App Warehouse and released as a version for GitHub.

The current `master-2.4` branch should be tagged `2.0.0`, built with Starcounter 2.4, packaged for App Warehouse and released as a version for GitHub.

This will allow @ubbeK to use Git tags in level1 (for issue https://github.com/Starcounter/Home/issues/326) as well as allow every app developer to use the released packages to do upgrades/downgrades of client files.

**Comment by alshakero** [comment]
Could you elaborate on "packaged for App Warehouse" please? Is there a special format or anything?

**Comment by alshakero** [comment]
Should be good now:
1. https://github.com/Starcounter/StarcounterClientFiles/releases
2. http://warehouse.starcounter.com/warehouse/organizations/starcounter/softwares/starcounterclientfiles

**Comment by alshakero** [comment]
Can I close this?

**Comment by warpech** [comment]
Yes, definitely. Thanks a 💯 !

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- announced on the Starcounter blog https://starcounter.io/starcounter-2-4-gets-upgrade-polymer-2/ ("Manual upgrade or downgrade to Polymer 1 and 2")
